#pragma once
#include <stdio.h>
#include <string>
#include "srpc/rpc_define.h"
#include "user_service.pb.h"

namespace user_service
{

namespace UserService
{

/*
 * Server codes
 * Generated by SRPC
 */

class Service : public srpc::RPCService
{
public:
	// please implement these methods in server.cc

	virtual void Signup(SignupRequest *request, SignupResponse *response,
					srpc::RPCContext *ctx) = 0;

	virtual void Signin(SignupRequest *request, SignupResponse *response,
					srpc::RPCContext *ctx) = 0;

	virtual void GetUserInfo(GetUserInfoRequest *request, GetUserInfoResponse *response,
					srpc::RPCContext *ctx) = 0;

public:
	Service();
};

/*
 * Client codes
 * Generated by SRPC
 */

using SignupDone = std::function<void (SignupResponse *, srpc::RPCContext *)>;
using SigninDone = std::function<void (SignupResponse *, srpc::RPCContext *)>;
using GetUserInfoDone = std::function<void (GetUserInfoResponse *, srpc::RPCContext *)>;

class SRPCClient : public srpc::SRPCClient
{
public:
	void Signup(const SignupRequest *req, SignupDone done);
	void Signup(const SignupRequest *req, SignupResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SignupResponse, srpc::RPCSyncContext>> async_Signup(const SignupRequest *req);

	void Signin(const SignupRequest *req, SigninDone done);
	void Signin(const SignupRequest *req, SignupResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SignupResponse, srpc::RPCSyncContext>> async_Signin(const SignupRequest *req);

	void GetUserInfo(const GetUserInfoRequest *req, GetUserInfoDone done);
	void GetUserInfo(const GetUserInfoRequest *req, GetUserInfoResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<GetUserInfoResponse, srpc::RPCSyncContext>> async_GetUserInfo(const GetUserInfoRequest *req);

public:
	SRPCClient(const char *host, unsigned short port);
	SRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCClientTask *create_Signup_task(SignupDone done);
	srpc::SRPCClientTask *create_Signin_task(SigninDone done);
	srpc::SRPCClientTask *create_GetUserInfo_task(GetUserInfoDone done);
};

class SRPCHttpClient : public srpc::SRPCHttpClient
{
public:
	void Signup(const SignupRequest *req, SignupDone done);
	void Signup(const SignupRequest *req, SignupResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SignupResponse, srpc::RPCSyncContext>> async_Signup(const SignupRequest *req);

	void Signin(const SignupRequest *req, SigninDone done);
	void Signin(const SignupRequest *req, SignupResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SignupResponse, srpc::RPCSyncContext>> async_Signin(const SignupRequest *req);

	void GetUserInfo(const GetUserInfoRequest *req, GetUserInfoDone done);
	void GetUserInfo(const GetUserInfoRequest *req, GetUserInfoResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<GetUserInfoResponse, srpc::RPCSyncContext>> async_GetUserInfo(const GetUserInfoRequest *req);

public:
	SRPCHttpClient(const char *host, unsigned short port);
	SRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::SRPCHttpClientTask *create_Signup_task(SignupDone done);
	srpc::SRPCHttpClientTask *create_Signin_task(SigninDone done);
	srpc::SRPCHttpClientTask *create_GetUserInfo_task(GetUserInfoDone done);
};

class BRPCClient : public srpc::BRPCClient
{
public:
	void Signup(const SignupRequest *req, SignupDone done);
	void Signup(const SignupRequest *req, SignupResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SignupResponse, srpc::RPCSyncContext>> async_Signup(const SignupRequest *req);

	void Signin(const SignupRequest *req, SigninDone done);
	void Signin(const SignupRequest *req, SignupResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SignupResponse, srpc::RPCSyncContext>> async_Signin(const SignupRequest *req);

	void GetUserInfo(const GetUserInfoRequest *req, GetUserInfoDone done);
	void GetUserInfo(const GetUserInfoRequest *req, GetUserInfoResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<GetUserInfoResponse, srpc::RPCSyncContext>> async_GetUserInfo(const GetUserInfoRequest *req);

public:
	BRPCClient(const char *host, unsigned short port);
	BRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::BRPCClientTask *create_Signup_task(SignupDone done);
	srpc::BRPCClientTask *create_Signin_task(SigninDone done);
	srpc::BRPCClientTask *create_GetUserInfo_task(GetUserInfoDone done);
};

class TRPCClient : public srpc::TRPCClient
{
public:
	void Signup(const SignupRequest *req, SignupDone done);
	void Signup(const SignupRequest *req, SignupResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SignupResponse, srpc::RPCSyncContext>> async_Signup(const SignupRequest *req);

	void Signin(const SignupRequest *req, SigninDone done);
	void Signin(const SignupRequest *req, SignupResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SignupResponse, srpc::RPCSyncContext>> async_Signin(const SignupRequest *req);

	void GetUserInfo(const GetUserInfoRequest *req, GetUserInfoDone done);
	void GetUserInfo(const GetUserInfoRequest *req, GetUserInfoResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<GetUserInfoResponse, srpc::RPCSyncContext>> async_GetUserInfo(const GetUserInfoRequest *req);

public:
	TRPCClient(const char *host, unsigned short port);
	TRPCClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCClientTask *create_Signup_task(SignupDone done);
	srpc::TRPCClientTask *create_Signin_task(SigninDone done);
	srpc::TRPCClientTask *create_GetUserInfo_task(GetUserInfoDone done);
};

class TRPCHttpClient : public srpc::TRPCHttpClient
{
public:
	void Signup(const SignupRequest *req, SignupDone done);
	void Signup(const SignupRequest *req, SignupResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SignupResponse, srpc::RPCSyncContext>> async_Signup(const SignupRequest *req);

	void Signin(const SignupRequest *req, SigninDone done);
	void Signin(const SignupRequest *req, SignupResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<SignupResponse, srpc::RPCSyncContext>> async_Signin(const SignupRequest *req);

	void GetUserInfo(const GetUserInfoRequest *req, GetUserInfoDone done);
	void GetUserInfo(const GetUserInfoRequest *req, GetUserInfoResponse *resp, srpc::RPCSyncContext *sync_ctx);
	WFFuture<std::pair<GetUserInfoResponse, srpc::RPCSyncContext>> async_GetUserInfo(const GetUserInfoRequest *req);

public:
	TRPCHttpClient(const char *host, unsigned short port);
	TRPCHttpClient(const struct srpc::RPCClientParams *params);

public:
	srpc::TRPCHttpClientTask *create_Signup_task(SignupDone done);
	srpc::TRPCHttpClientTask *create_Signin_task(SigninDone done);
	srpc::TRPCHttpClientTask *create_GetUserInfo_task(GetUserInfoDone done);
};

///// implements detials /////

inline Service::Service(): srpc::RPCService("user_service.UserService")
{
	this->srpc::RPCService::add_method("Signup",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::Signup);
		});

	this->srpc::RPCService::add_method("Signin",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::Signin);
		});

	this->srpc::RPCService::add_method("GetUserInfo",
		[this](srpc::RPCWorker& worker) ->int {
			return ServiceRPCCallImpl(this, worker, &Service::GetUserInfo);
		});
}

inline SRPCClient::SRPCClient(const char *host, unsigned short port):
	srpc::SRPCClient("user_service.UserService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCClient::init(&params);
}

inline SRPCClient::SRPCClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCClient("user_service.UserService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCClient::init(temp);
}

inline void SRPCClient::Signup(const SignupRequest *req, SignupDone done)
{
	auto *task = this->create_rpc_client_task("Signup", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::Signup(const SignupRequest *req, SignupResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Signup(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SignupResponse, srpc::RPCSyncContext>> SRPCClient::async_Signup(const SignupRequest *req)
{
	using RESULT = std::pair<SignupResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SignupResponse>("Signup", srpc::RPCAsyncFutureCallback<SignupResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCClient::Signin(const SignupRequest *req, SigninDone done)
{
	auto *task = this->create_rpc_client_task("Signin", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::Signin(const SignupRequest *req, SignupResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Signin(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SignupResponse, srpc::RPCSyncContext>> SRPCClient::async_Signin(const SignupRequest *req)
{
	using RESULT = std::pair<SignupResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SignupResponse>("Signin", srpc::RPCAsyncFutureCallback<SignupResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCClient::GetUserInfo(const GetUserInfoRequest *req, GetUserInfoDone done)
{
	auto *task = this->create_rpc_client_task("GetUserInfo", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCClient::GetUserInfo(const GetUserInfoRequest *req, GetUserInfoResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_GetUserInfo(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<GetUserInfoResponse, srpc::RPCSyncContext>> SRPCClient::async_GetUserInfo(const GetUserInfoRequest *req)
{
	using RESULT = std::pair<GetUserInfoResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<GetUserInfoResponse>("GetUserInfo", srpc::RPCAsyncFutureCallback<GetUserInfoResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCClientTask *SRPCClient::create_Signup_task(SignupDone done)
{
	return this->create_rpc_client_task("Signup", std::move(done));
}

inline srpc::SRPCClientTask *SRPCClient::create_Signin_task(SigninDone done)
{
	return this->create_rpc_client_task("Signin", std::move(done));
}

inline srpc::SRPCClientTask *SRPCClient::create_GetUserInfo_task(GetUserInfoDone done)
{
	return this->create_rpc_client_task("GetUserInfo", std::move(done));
}

inline SRPCHttpClient::SRPCHttpClient(const char *host, unsigned short port):
	srpc::SRPCHttpClient("user_service/UserService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::SRPCHttpClient::init(&params);
}

inline SRPCHttpClient::SRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::SRPCHttpClient("user_service/UserService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::SRPCHttpClient::init(temp);
}

inline void SRPCHttpClient::Signup(const SignupRequest *req, SignupDone done)
{
	auto *task = this->create_rpc_client_task("Signup", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::Signup(const SignupRequest *req, SignupResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Signup(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SignupResponse, srpc::RPCSyncContext>> SRPCHttpClient::async_Signup(const SignupRequest *req)
{
	using RESULT = std::pair<SignupResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SignupResponse>("Signup", srpc::RPCAsyncFutureCallback<SignupResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCHttpClient::Signin(const SignupRequest *req, SigninDone done)
{
	auto *task = this->create_rpc_client_task("Signin", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::Signin(const SignupRequest *req, SignupResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Signin(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SignupResponse, srpc::RPCSyncContext>> SRPCHttpClient::async_Signin(const SignupRequest *req)
{
	using RESULT = std::pair<SignupResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SignupResponse>("Signin", srpc::RPCAsyncFutureCallback<SignupResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void SRPCHttpClient::GetUserInfo(const GetUserInfoRequest *req, GetUserInfoDone done)
{
	auto *task = this->create_rpc_client_task("GetUserInfo", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void SRPCHttpClient::GetUserInfo(const GetUserInfoRequest *req, GetUserInfoResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_GetUserInfo(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<GetUserInfoResponse, srpc::RPCSyncContext>> SRPCHttpClient::async_GetUserInfo(const GetUserInfoRequest *req)
{
	using RESULT = std::pair<GetUserInfoResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<GetUserInfoResponse>("GetUserInfo", srpc::RPCAsyncFutureCallback<GetUserInfoResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_Signup_task(SignupDone done)
{
	return this->create_rpc_client_task("Signup", std::move(done));
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_Signin_task(SigninDone done)
{
	return this->create_rpc_client_task("Signin", std::move(done));
}

inline srpc::SRPCHttpClientTask *SRPCHttpClient::create_GetUserInfo_task(GetUserInfoDone done)
{
	return this->create_rpc_client_task("GetUserInfo", std::move(done));
}

inline BRPCClient::BRPCClient(const char *host, unsigned short port):
	srpc::BRPCClient("user_service.UserService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::BRPCClient::init(&params);
}

inline BRPCClient::BRPCClient(const struct srpc::RPCClientParams *params):
	srpc::BRPCClient("user_service.UserService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::BRPCClient::init(temp);
}

inline void BRPCClient::Signup(const SignupRequest *req, SignupDone done)
{
	auto *task = this->create_rpc_client_task("Signup", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::Signup(const SignupRequest *req, SignupResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Signup(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SignupResponse, srpc::RPCSyncContext>> BRPCClient::async_Signup(const SignupRequest *req)
{
	using RESULT = std::pair<SignupResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SignupResponse>("Signup", srpc::RPCAsyncFutureCallback<SignupResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void BRPCClient::Signin(const SignupRequest *req, SigninDone done)
{
	auto *task = this->create_rpc_client_task("Signin", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::Signin(const SignupRequest *req, SignupResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Signin(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SignupResponse, srpc::RPCSyncContext>> BRPCClient::async_Signin(const SignupRequest *req)
{
	using RESULT = std::pair<SignupResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SignupResponse>("Signin", srpc::RPCAsyncFutureCallback<SignupResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void BRPCClient::GetUserInfo(const GetUserInfoRequest *req, GetUserInfoDone done)
{
	auto *task = this->create_rpc_client_task("GetUserInfo", std::move(done));

	task->serialize_input(req);
	task->start();
}

inline void BRPCClient::GetUserInfo(const GetUserInfoRequest *req, GetUserInfoResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_GetUserInfo(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<GetUserInfoResponse, srpc::RPCSyncContext>> BRPCClient::async_GetUserInfo(const GetUserInfoRequest *req)
{
	using RESULT = std::pair<GetUserInfoResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<GetUserInfoResponse>("GetUserInfo", srpc::RPCAsyncFutureCallback<GetUserInfoResponse>);

	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::BRPCClientTask *BRPCClient::create_Signup_task(SignupDone done)
{
	return this->create_rpc_client_task("Signup", std::move(done));
}

inline srpc::BRPCClientTask *BRPCClient::create_Signin_task(SigninDone done)
{
	return this->create_rpc_client_task("Signin", std::move(done));
}

inline srpc::BRPCClientTask *BRPCClient::create_GetUserInfo_task(GetUserInfoDone done)
{
	return this->create_rpc_client_task("GetUserInfo", std::move(done));
}

inline TRPCClient::TRPCClient(const char *host, unsigned short port):
	srpc::TRPCClient("user_service.UserService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCClient::init(&params);
}

inline TRPCClient::TRPCClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCClient("user_service.UserService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCClient::init(temp);
}

inline void TRPCClient::Signup(const SignupRequest *req, SignupDone done)
{
	auto *task = this->create_rpc_client_task("/user_service.UserService/Signup", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::Signup(const SignupRequest *req, SignupResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Signup(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SignupResponse, srpc::RPCSyncContext>> TRPCClient::async_Signup(const SignupRequest *req)
{
	using RESULT = std::pair<SignupResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SignupResponse>("/user_service.UserService/Signup", srpc::RPCAsyncFutureCallback<SignupResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCClient::Signin(const SignupRequest *req, SigninDone done)
{
	auto *task = this->create_rpc_client_task("/user_service.UserService/Signin", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::Signin(const SignupRequest *req, SignupResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Signin(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SignupResponse, srpc::RPCSyncContext>> TRPCClient::async_Signin(const SignupRequest *req)
{
	using RESULT = std::pair<SignupResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SignupResponse>("/user_service.UserService/Signin", srpc::RPCAsyncFutureCallback<SignupResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCClient::GetUserInfo(const GetUserInfoRequest *req, GetUserInfoDone done)
{
	auto *task = this->create_rpc_client_task("/user_service.UserService/GetUserInfo", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCClient::GetUserInfo(const GetUserInfoRequest *req, GetUserInfoResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_GetUserInfo(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<GetUserInfoResponse, srpc::RPCSyncContext>> TRPCClient::async_GetUserInfo(const GetUserInfoRequest *req)
{
	using RESULT = std::pair<GetUserInfoResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<GetUserInfoResponse>("/user_service.UserService/GetUserInfo", srpc::RPCAsyncFutureCallback<GetUserInfoResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCClientTask *TRPCClient::create_Signup_task(SignupDone done)
{
	auto *task = this->create_rpc_client_task("/user_service.UserService/Signup", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCClientTask *TRPCClient::create_Signin_task(SigninDone done)
{
	auto *task = this->create_rpc_client_task("/user_service.UserService/Signin", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCClientTask *TRPCClient::create_GetUserInfo_task(GetUserInfoDone done)
{
	auto *task = this->create_rpc_client_task("/user_service.UserService/GetUserInfo", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline TRPCHttpClient::TRPCHttpClient(const char *host, unsigned short port):
	srpc::TRPCHttpClient("user_service.UserService")
{
	struct srpc::RPCClientParams params = srpc::RPC_CLIENT_PARAMS_DEFAULT;
	
	params.host = host;
	params.port = port;
	this->srpc::TRPCHttpClient::init(&params);
}

inline TRPCHttpClient::TRPCHttpClient(const struct srpc::RPCClientParams *params):
	srpc::TRPCHttpClient("user_service.UserService")
{
	const struct srpc::RPCClientParams *temp = params;
	struct srpc::RPCClientParams temp_params;
	
	this->srpc::TRPCHttpClient::init(temp);
}

inline void TRPCHttpClient::Signup(const SignupRequest *req, SignupDone done)
{
	auto *task = this->create_rpc_client_task("Signup", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::Signup(const SignupRequest *req, SignupResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Signup(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SignupResponse, srpc::RPCSyncContext>> TRPCHttpClient::async_Signup(const SignupRequest *req)
{
	using RESULT = std::pair<SignupResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SignupResponse>("Signup", srpc::RPCAsyncFutureCallback<SignupResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCHttpClient::Signin(const SignupRequest *req, SigninDone done)
{
	auto *task = this->create_rpc_client_task("Signin", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::Signin(const SignupRequest *req, SignupResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_Signin(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<SignupResponse, srpc::RPCSyncContext>> TRPCHttpClient::async_Signin(const SignupRequest *req)
{
	using RESULT = std::pair<SignupResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<SignupResponse>("Signin", srpc::RPCAsyncFutureCallback<SignupResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline void TRPCHttpClient::GetUserInfo(const GetUserInfoRequest *req, GetUserInfoDone done)
{
	auto *task = this->create_rpc_client_task("GetUserInfo", std::move(done));

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->start();
}

inline void TRPCHttpClient::GetUserInfo(const GetUserInfoRequest *req, GetUserInfoResponse *resp, srpc::RPCSyncContext *sync_ctx)
{
	auto res = this->async_GetUserInfo(req).get();

	if (resp && res.second.success)
		*resp = std::move(res.first);

	if (sync_ctx)
		*sync_ctx = std::move(res.second);
}

inline WFFuture<std::pair<GetUserInfoResponse, srpc::RPCSyncContext>> TRPCHttpClient::async_GetUserInfo(const GetUserInfoRequest *req)
{
	using RESULT = std::pair<GetUserInfoResponse, srpc::RPCSyncContext>;
	auto *pr = new WFPromise<RESULT>();
	auto fr = pr->get_future();
	auto *task = this->create_rpc_client_task<GetUserInfoResponse>("GetUserInfo", srpc::RPCAsyncFutureCallback<GetUserInfoResponse>);

	if (this->params.callee_timeout >= 0)
		task->get_req()->set_callee_timeout(this->params.callee_timeout);
	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);
	task->serialize_input(req);
	task->user_data = pr;
	task->start();
	return fr;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_Signup_task(SignupDone done)
{
	auto *task = this->create_rpc_client_task("Signup", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_Signin_task(SigninDone done)
{
	auto *task = this->create_rpc_client_task("Signin", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

inline srpc::TRPCHttpClientTask *TRPCHttpClient::create_GetUserInfo_task(GetUserInfoDone done)
{
	auto *task = this->create_rpc_client_task("GetUserInfo", std::move(done));

	if (!this->params.caller.empty())
		task->get_req()->set_caller_name(this->params.caller);

	return task;
}

} // end namespace UserService

} // end namespace user_service

